apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRYWsxUWdma3lEbTNFVlViWjVjWG9wekFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRd05EaGtZalppWkMxa05qSTJMVFJtWW1NdFlqWTBNUzA0WVdVNFpHUXpOMkU0Tm1ZdwpJQmNOTWpRd056RTJNRGcxT1RRNFdoZ1BNakExTkRBM01Ea3dPVFU1TkRoYU1DOHhMVEFyQmdOVkJBTVRKREEwCk9HUmlObUprTFdRMk1qWXROR1ppWXkxaU5qUXhMVGhoWlRoa1pETTNZVGcyWmpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQU5WWERYS0I3QXVSaG8zVGtCQWVMMXZHYllYM1kxckZTS3MzQ0pIVAowbWpETE84bDZKTXltNWlCQmMrOHdqRWZyOHFZQ1JvaDJYTXphRGIyOTRIeUw4cEZxUE4rWitzajdxekRRdnhkCmNFZmZEMTZkVmxLSWVvem9ueDB6b3d5QWtaZ014cTlMRWh2VnNOem9BSm1ydmV0Wk5hL0toZ3hEemFHeVVGbE8KazRTeUZJTnJVNGtnMWFqK2cySmxKRWFFbExFVGZHUFFQZkpOODZ4NUh3QWhXQ0R5Zm9OQVdFcVluV0NmSkRQZApzZHpBdkVyZG1tMjh5OU1nNVFDTjIwWUlxVDQvVk5VcTE5MU9sbnhzRG5VNHVWL2FRcFFTeVZ3NzFzblBQV2N3CmxVZklpR1E2Snd2azBTM24wSUN1cCs5ck50SWF0V29pdjV5aGZ1WHhLQVJNNEJVU01SWlUyZWp5U2Y0SS84V0kKRktxanFWN0hCYU5UUWc5ZkVMUm5EcEE5Rll1OFlPNnZOVnFQS3F3QWJmY1JXTS9uczFkdUpvT1ZuaUZyMkx0Vgp0dEdKS0JDWnMvcFNYc0dUeUUyWGFPNlZjbXowVkVxQ2VIcmR2QjB3czFvcFZnT003OG5DSGRuMitiR1VYajdoCk1mMEdjMzhEcXBUR05YVzZMY1dXNWZidTZRSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVVZ2Z1cGJBM0RNN1JWWG9zOGQyZldZQXdab2d3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFKajN0ZVNvMnFDOHRJeU9WcTNBcFpIVEpnMW5hQk82UW82QXo2a2ZSREFiCmo5WkZFUFlYR2JQUEhYRzZJMkpKMjZpOXphRUxYVVhjb2trcVFNcElkY0N5QnZ3eTBxV1JoMU1tMy9QbGNlanEKbHFwTXFDU3VoZ0hBK2UvQm5YMTVjYUdBZHF1QTJnYW9laUFKUCtvZ29rVUpKMzBxR245N040REQrSVJDQ055cgpkUGtUSjUxZ1djRlMrZlllQ3JjVVk0ZzZGb1BaWjdTbURWMHB4UC9KaWpwZnBxQVRYUklNZUJCRkRxY01DNjlpCjFrelBJdzNpdVVYT2xubFJ3Z3NGN1Ntdit4YW5QcDdNblFhS0QvNzY5UUEweWVnK0M0RDB3M2g1RUpNblpXSTkKbzlUTjVrOU1NMGNaT0NqdzhsejRYTEF3RVpHTnFFV1hWTVdCSHk1R2tyc05Ec1Z3TENmcU9rSUpkdmVqcWhSQgpiL1hqN0h1UUNDS3FGS2RxOHFYSzcrbXZzT1FzcG9pWEZFb3RKOVI2VWYrczVoL25YVUdMNzFCR05iVUk0N1c0CmZrMHJZMTl3WU1kTk5NbkFJVXRxa1lDRldMTThBeFY0RmIrUWhhaWt2LzV4anphWlVoeER5Sy9XTzNGZkV5SkcKOE9yVDljWCtHQng0V1Ztbm85Slp4UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.170.206.173
  name: gke_itm350-project_us-central1-f_itm350-cluster
contexts:
- context:
    cluster: gke_itm350-project_us-central1-f_itm350-cluster
    user: gke_itm350-project_us-central1-f_itm350-cluster
  name: gke_itm350-project_us-central1-f_itm350-cluster
current-context: gke_itm350-project_us-central1-f_itm350-cluster
kind: Config
preferences: {}
users:
- name: gke_itm350-project_us-central1-f_itm350-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true