name: build-push.yaml

on:
  pull_request:
    branches: 
      - main
    types:
      - closed

env:
  REPO_NAME: vukanim/itm350-vukanim-bb

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPO_NAME }}
          tags: |
            type=sha

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: bulletin-board-app/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      #- name: Set active account
        #run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        run: gcloud container clusters get-credentials itm350-cluster --zone us-central1-f --project itm350-project
      - name: Deploy to GKE
        run: kubectl apply -f service.yaml --validate=false
